import type { PlatformConfig } from "@/types";

export const PLATFORMS: PlatformConfig[] = [
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Pull MQLs, SQOs, pipeline, deals, and revenue from your CRM.",
    authMethod: "token",
    channel: "all",
    color: "#FF7A59",
    logo: "/logos/hubspot.svg",
    docsUrl: "https://developers.hubspot.com/docs/api/private-apps",
    setupSteps: [
      "Go to HubSpot Settings → Integrations → Private Apps",
      "Click 'Create a private app' and give it a name (e.g. Marketing Dashboard)",
      "Under Scopes, enable: crm.objects.contacts.read, crm.objects.deals.read, crm.schemas.deals.read, analytics.read, crm.objects.companies.read",
      "Click 'Create app', then copy the access token and paste it below",
    ],
    fields: [
      {
        key: "accessToken",
        label: "Private App Token",
        placeholder: "pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
        type: "password",
        hint: "Found in HubSpot Settings → Integrations → Private Apps",
      },
    ],
  },
  {
    id: "google_ads",
    name: "Google Ads",
    description: "Pull spend, impressions, clicks, and conversions from all campaigns.",
    authMethod: "oauth",
    oauthPath: "/api/oauth/google",
    channel: "paid_media",
    color: "#4285F4",
    logo: "/logos/google-ads.svg",
    docsUrl: "https://developers.google.com/google-ads/api/docs/oauth/overview",
    oauthScopes: ["https://www.googleapis.com/auth/adwords"],
    setupSteps: [
      "In Google Cloud Console, create a project and enable the Google Ads API",
      "Go to APIs & Services → Credentials → Create OAuth Client ID (Web application)",
      "Add http://localhost:3001/api/oauth/google/callback as an authorised redirect URI",
      "Paste your Client ID and Client Secret below, then click Authorise with Google",
    ],
    credentialFields: [
      {
        key: "clientId",
        label: "Client ID",
        placeholder: "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
        type: "text" as const,
        hint: "Found in Google Cloud Console → APIs & Services → Credentials",
      },
      {
        key: "clientSecret",
        label: "Client Secret",
        placeholder: "GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password" as const,
        hint: "Found next to your Client ID in Google Cloud Console",
      },
      {
        key: "customerId",
        label: "Google Ads Customer ID",
        placeholder: "123-456-7890",
        type: "text" as const,
        hint: "Found in the top-right of Google Ads — format: XXX-XXX-XXXX",
      },
    ],
  },
  {
    id: "google_search_console",
    name: "Google Search Console",
    description: "Pull organic impressions, clicks, and keyword data.",
    authMethod: "oauth",
    oauthPath: "/api/oauth/google",
    channel: "organic",
    color: "#34A853",
    logo: "/logos/google-search-console.svg",
    docsUrl: "https://developers.google.com/webmaster-tools/search-console-api",
    oauthScopes: ["https://www.googleapis.com/auth/webmasters.readonly"],
    setupSteps: [
      "Uses the same Google OAuth app as Google Ads — connect Google Ads first",
      "Once Google Ads is authorised, Search Console will connect automatically",
    ],
  },
  {
    id: "facebook",
    name: "Facebook Business Manager",
    description: "Pull paid social spend, reach, clicks, and lead data.",
    authMethod: "token",
    channel: "paid_media",
    color: "#1877F2",
    logo: "/logos/facebook.svg",
    docsUrl: "https://developers.facebook.com/docs/marketing-api/system-users",
    setupSteps: [
      "Go to Business Manager → Business Settings → System Users",
      "Create or select a System User, then click Generate New Token",
      "Select the Ad Account you want to connect and grant ads_read permission",
      "Copy the token and your Ad Account ID below",
    ],
    fields: [
      {
        key: "accessToken",
        label: "System User Access Token",
        placeholder: "EAAxxxxxxxxxxxxxxx...",
        type: "password",
        hint: "Long-lived token from Business Manager → System Users",
      },
      {
        key: "tokenSecret",
        label: "Ad Account ID",
        placeholder: "act_1234567890",
        type: "text",
        hint: "Found in Ads Manager — format: act_XXXXXXXXXX",
      },
    ],
  },
  {
    id: "linkedin",
    name: "LinkedIn Campaign Manager",
    description: "Pull paid social spend, impressions, clicks, and lead gen data.",
    authMethod: "oauth",
    channel: "paid_media",
    color: "#0A66C2",
    logo: "/logos/linkedin.svg",
    docsUrl: "https://learn.microsoft.com/en-us/linkedin/marketing/",
    oauthScopes: ["r_ads", "r_ads_reporting"],
    setupSteps: [
      "Go to LinkedIn Developer Portal → Create App",
      "Under Auth, add http://localhost:3001/api/oauth/linkedin/callback as a redirect URL",
      "Request access to the Marketing Developer Platform products",
      "Paste your Client ID and Client Secret below, then click Authorise with LinkedIn",
    ],
    credentialFields: [
      {
        key: "clientId",
        label: "Client ID",
        placeholder: "xxxxxxxxxxxxxxxxx",
        type: "text" as const,
        hint: "Found in LinkedIn Developer Portal → Your App → Auth",
      },
      {
        key: "clientSecret",
        label: "Client Secret",
        placeholder: "xxxxxxxxxxxxxxxx",
        type: "password" as const,
        hint: "Found next to Client ID in LinkedIn Developer Portal",
      },
    ],
  },
  {
    id: "reddit",
    name: "Reddit Advertising",
    description: "Pull paid social spend, impressions, clicks, and conversion data.",
    authMethod: "token",
    channel: "paid_media",
    color: "#FF4500",
    logo: "/logos/reddit.svg",
    docsUrl: "https://ads-api.reddit.com/docs/",
    setupSteps: [
      "Go to Reddit Ads → API Access (or reddit.com/prefs/apps)",
      "Create a new app of type 'script'",
      "Copy the App ID (client_id) and Secret below",
    ],
    fields: [
      {
        key: "accessToken",
        label: "Client ID (App ID)",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxx",
        type: "text",
        hint: "The short string under your app name on reddit.com/prefs/apps",
      },
      {
        key: "tokenSecret",
        label: "Client Secret",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password",
        hint: "The secret shown next to your app",
      },
    ],
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    description: "Pull data from your internal model or planning spreadsheet into the dashboard.",
    authMethod: "oauth",
    oauthPath: "/api/oauth/google-sheets",
    color: "#0F9D58",
    logo: "/logos/google-sheets.svg",
    docsUrl: "https://developers.google.com/sheets/api/guides/concepts",
    oauthScopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
    setupSteps: [
      "Go to console.cloud.google.com and open (or create) a project",
      "Navigate to APIs & Services → Library, search for 'Google Sheets API', and enable it",
      "Go to APIs & Services → Credentials → Create Credentials → OAuth client ID → Web application",
      "Under 'Authorised redirect URIs' add: http://localhost:3001/api/oauth/google-sheets/callback",
      "Copy your Client ID and Client Secret and paste them below along with your Spreadsheet ID",
      "Click 'Authorise with Google' and sign in with the account that has access to the sheet",
    ],
    credentialFields: [
      {
        key: "clientId",
        label: "Client ID",
        placeholder: "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
        type: "text" as const,
        hint: "Found in Google Cloud Console → APIs & Services → Credentials",
      },
      {
        key: "clientSecret",
        label: "Client Secret",
        placeholder: "GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password" as const,
        hint: "Found next to your Client ID in Google Cloud Console",
      },
      {
        key: "spreadsheetId",
        label: "Spreadsheet ID",
        placeholder: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms",
        type: "text" as const,
        hint: "The long ID in your sheet URL: docs.google.com/spreadsheets/d/{ID}/edit",
      },
    ],
  },
  {
    id: "google_analytics",
    name: "Google Analytics",
    description: "Pull sessions, users, traffic sources, and conversion data from your GA4 property.",
    authMethod: "oauth",
    oauthPath: "/api/oauth/google-analytics",
    color: "#E37400",
    logo: "/logos/google-analytics.svg",
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
    oauthScopes: ["https://www.googleapis.com/auth/analytics.readonly"],
    setupSteps: [
      "Go to console.cloud.google.com and open (or create) a project",
      "Navigate to APIs & Services → Library, enable both 'Google Analytics Data API' and 'Google Analytics Admin API'",
      "Go to APIs & Services → Credentials → Create Credentials → OAuth client ID → Web application",
      `Under 'Authorised redirect URIs' add: ${process.env.NEXTAUTH_URL ?? "http://localhost:3001"}/api/oauth/google-analytics/callback`,
      "Copy your Client ID and Client Secret and paste them below along with your GA4 Property ID",
      "Click 'Authorise with Google' and sign in with an account that has access to the property",
    ],
    credentialFields: [
      {
        key: "clientId",
        label: "Client ID",
        placeholder: "xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com",
        type: "text" as const,
        hint: "Found in Google Cloud Console → APIs & Services → Credentials",
      },
      {
        key: "clientSecret",
        label: "Client Secret",
        placeholder: "GOCSPX-xxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password" as const,
        hint: "Found next to your Client ID in Google Cloud Console",
      },
      {
        key: "propertyId",
        label: "GA4 Property ID",
        placeholder: "123456789",
        type: "text" as const,
        hint: "Found in GA4 → Admin → Property Settings (numeric ID only, e.g. 123456789)",
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic AI",
    description: "Powers the AI Insight panel on every metric card — ask questions about your data.",
    authMethod: "token",
    color: "#D97706",
    logo: "/logos/anthropic.svg",
    docsUrl: "https://console.anthropic.com/",
    setupSteps: [
      "Go to console.anthropic.com and sign in (or create a free account)",
      "Navigate to Settings → API Keys",
      "Click 'Create Key', give it a name (e.g. Marketing Dashboard), and copy the key",
      "Paste the key below — it starts with sk-ant-",
    ],
    fields: [
      {
        key: "accessToken",
        label: "API Key",
        placeholder: "sk-ant-api03-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password",
        hint: "Found in Anthropic Console → Settings → API Keys",
      },
    ],
  },
];

export const PLATFORM_MAP = Object.fromEntries(PLATFORMS.map((p) => [p.id, p])) as Record<string, PlatformConfig>;
